// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbQyFENN1jKfXQsJ01zSbj3GkS4Cbh-V4',
    appId: '1:1027872697293:web:c53c7955ce83475a883284',
    messagingSenderId: '1027872697293',
    projectId: 'wafraapp-127e2',
    authDomain: 'wafraapp-127e2.firebaseapp.com',
    storageBucket: 'wafraapp-127e2.firebasestorage.app',
    measurementId: 'G-5F60C3FZXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_mtBD3Txq4WJo1UdLODMlEjOPwy_pJHU',
    appId: '1:1027872697293:android:28aca41a83838e08883284',
    messagingSenderId: '1027872697293',
    projectId: 'wafraapp-127e2',
    storageBucket: 'wafraapp-127e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJrb1nf5-ZNQ3X0uKs5-GguwhYmg4axSY',
    appId: '1:1027872697293:ios:b97f0927f5ed000e883284',
    messagingSenderId: '1027872697293',
    projectId: 'wafraapp-127e2',
    storageBucket: 'wafraapp-127e2.firebasestorage.app',
    iosBundleId: 'com.example.testt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJrb1nf5-ZNQ3X0uKs5-GguwhYmg4axSY',
    appId: '1:1027872697293:ios:b97f0927f5ed000e883284',
    messagingSenderId: '1027872697293',
    projectId: 'wafraapp-127e2',
    storageBucket: 'wafraapp-127e2.firebasestorage.app',
    iosBundleId: 'com.example.testt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbQyFENN1jKfXQsJ01zSbj3GkS4Cbh-V4',
    appId: '1:1027872697293:web:cce2c8d197e8fc4a883284',
    messagingSenderId: '1027872697293',
    projectId: 'wafraapp-127e2',
    authDomain: 'wafraapp-127e2.firebaseapp.com',
    storageBucket: 'wafraapp-127e2.firebasestorage.app',
    measurementId: 'G-ZMFWQS7FT4',
  );
}
